services:
  postgres-demo:
    image: postgres:13
    container_name: reddit_post_psql_ingestion
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    restart: always

  minio:
    image: minio/minio:latest
    container_name: reddit_post_minio_ingestion
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
